### ISSUE TITLE
help with a bash mutt script

### ISSUE THREAD

**Issue by fmontaldo** [cbracken/mutt#1]
Hi Chris,

Sorry to bother you but I am trying to figure it out the way to configure a bash script for mutt. I am asking to everyone who knows about. Can you please help me?.

Regards

**Comment by cbracken** [comment]
Apologies, unfortunately I don't have time to analyse mutt issues these days. I'd suggest you post a question with details on StackOverflow's [mutt](https://stackoverflow.com/questions/tagged/mutt) section.
